version: '3.9'
services:
    mysql:
        image: mysql:5.7
        restart: always
        ports:
            - 3306:3306
        volumes:
            - "./.srv/database:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD:  wordpress
            MYSQL_DATABASE: ale-app
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    wordpress:
        image: wordpress:latest
        depends_on:
            - mysql
        links:
            - mysql
        ports:
            - 8000:80
        restart: always
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: ale-app
            WORDPRESS_DEBUG: 1
            WORDPRESS_CONFIG_EXTRA: |
                define('FS_METHOD', 'direct');
        volumes:
            - ./dist/theme/:/var/www/html/wp-content/themes/ale
            - ./dist/plugin:/var/www/html/wp-content/plugins/ale-core
            - ./.srv/wordpress/:/var/www/html
            - ./.srv/log/:/var/log
            - './.srv/custom.ini:/usr/local/etc/php/conf.d/custom.ini'

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - mysql
        links:
            - mysql:mysql
        ports:
            - 8181:80
        restart: always
        environment:
            MYSQL_USERNAME: wordpress
            MYSQL_ROOT_PASSWORD: wordpress
            PMA_HOST: mysql
        volumes:
            - './.srv/custom.ini:/usr/local/etc/php/conf.d/custom.ini'

    mailhog:
        image: mailhog/mailhog
        ports:
            - 1025:1025 # smtp server
            - 8025:8025 # web ui
